# **Inferential Analysis**

In [12]:
import pandas as pd
import scipy.stats as stats
pd.set_option('display.float_format', '{:.10f}'.format)

In [ ]:
df = pd.read_csv("dataset\\digital_marketing_campaign_dataset.csv").drop(columns=["CustomerID", "AdvertisingPlatform", "AdvertisingTool"])

## **1. Chi-Square Test for `Categorical Variables`**

### **Objective**: determine if there is a relationship between  `categorical variables` and `Conversion`

**Testing Variable**: `Gender`, `CampaignChannel`, `CampaignType`

### **Hypothesis**
- **H₀ (Null Hypothesis)**: testing variable and `Conversion` are **independent**.  
- **Hₐ (Alternative Hypothesis)**: testing variable and `Conversion` are **dependent**.

In [14]:
cat_vars = ["Gender", "CampaignChannel", "CampaignType"]
results = []
for var in cat_vars:
    contigency_table = pd.crosstab(df[var], df["Conversion"])
    chi2, p, dof, expected = stats.chi2_contingency(contigency_table)
    results.append({
        "Variable" : var,
        "P-value" : p,
        "Support Hₐ" : True if p < 0.05 else False
    })
pd.DataFrame(results)

          Variable      P-value  Support Hₐ
0           Gender 0.9510312300       False
1  CampaignChannel 0.5944499904       False
2     CampaignType 0.0000000000        True

## **2. Mann-Whitney U Test for `Numerical Variables`**

### **Objective:** To test whether the medians/distributions of numerical variables differ significantly between the `Conversion = 0` and `Conversion = 1` groups.
**Variables Tested**: `Age`, `Income`, `AdSpend`, `ClickThroughRate`, `ConversionRate`, `WebsiteVisits`, `PagesPerVisit`, `TimeOnSite`, `SocialShares`, `EmailOpens`, `EmailClicks`, `PreviousPurchases`, `LoyaltyPoints`
### **Hypothesis**
- **H₀ (Null Hypothesis)**: There is **no difference** in the distribution/median of the variable between the two conversion groups.  
- **Hₐ (Alternative Hypothesis)**: There is a **significant difference** in the distribution/median of the variable between the two conversion groups.

In [18]:
num_vars = df.select_dtypes(include="number").columns
results = []

for var in num_vars:
    group0 = df[df['Conversion'] == 0][var]
    group1 = df[df['Conversion'] == 1][var]
    u_stat, p_mw = stats.mannwhitneyu(group0, group1, alternative='two-sided')
    results.append({
        "variable" : var,
        "p_value" : p_mw,
        "Support Hₐ" : True if p_mw < 0.05 else False 
    })
pd.DataFrame(results)

             variable      p_value  Support Hₐ
0                 Age 0.8828806619       False
1              Income 0.2104402596       False
2             AdSpend 0.0000000000        True
3    ClickThroughRate 0.0000000000        True
4      ConversionRate 0.0000000000        True
5       WebsiteVisits 0.0000000000        True
6       PagesPerVisit 0.0000000000        True
7          TimeOnSite 0.0000000000        True
8        SocialShares 0.3037988621       False
9          EmailOpens 0.0000000000        True
10        EmailClicks 0.0000000000        True
11  PreviousPurchases 0.0000000000        True
12      LoyaltyPoints 0.0000000000        True
13         Conversion 0.0000000000        True

## **3. Conclusion**
After conducting `Chi-square` and `Mann-Whitney U` tests, the following variables show statistically significant relationships with Conversion: <br>
- Recommended variables to keep (10 variables):
`CampaignType`, 
`TimeOnSite`, 
`EmailClicks`, 
`AdSpend`, 
`PagesPerVisit`, 
`EmailOpens`, 
`PreviousPurchases`, 
`LoyaltyPoints`, 
`ClickThroughRate`, 
`WebsiteVisits` <br>

- Variables to exclude: `Age`, `Income`, `SocialShares`, `Gender`, `CampaignChannel` <br>

These variables have p-values > 0.05 in both statistical tests, indicating no significant relationship with the target variable Conversion. `ConversionRate` shows strong significance but should be excluded from the predictive model due to high risk of data leakage.