# **Deep Residual MLP**

## **1. Import Libraries**

In [112]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from residual_mlp_pipeline import train_and_evaluate

## **2. Hyperparameter Configuration**

In [113]:
config = {
    "file_path": r"dataset\\digital_marketing_campaign_dataset.csv",
    "seed": 42,
    "hidden_dim": 16,
    "num_blocks": 1,
    "head_dim": 8,
    "dropout": 0.7,
    "batch_size": 128,
    "lr": 3e-4,
    "weight_decay": 1e-2,
    "epochs": 120,
    "patience": 15,
    "threshold": 0.5,
    "noise_std": 0.03,
    "lr_factor": 0.5,
    "lr_patience": 5,
    "lr_min": 1e-5,
}

## **3. Training**

In [114]:
result = train_and_evaluate(config)
print("Training complete.")
print("AUC train:", round(result["roc_auc_train"], 4), "| AUC test:", round(result["roc_auc_test"], 4), "| gap:", round(result["auc_gap"], 4))

Training complete.
AUC train: 0.7986 | AUC test: 0.7657 | gap: 0.0329

## **4. Predict Testing Dataset**

In [115]:
y_test_prob = result["y_test_prob"]
print("Predicted test probs:", y_test_prob.shape)

Predicted test probs: (1600,)

## **5. Evaluation**

In [116]:
result["summary"]

                 Metric   Score
0       Accuracy (Test)  0.7481
1       ROC-AUC (Train)  0.7986
2        ROC-AUC (Test)  0.7657
3  AUC Gap (Train-Test)  0.0329

In [117]:
result["report_df"]

                   precision  recall  f1-score    support
Not Converted (0)     0.2869  0.6970    0.4065   198.0000
Converted (1)         0.9464  0.7553    0.8401  1402.0000
accuracy              0.7481  0.7481    0.7481     0.7481
macro avg             0.6166  0.7262    0.6233  1600.0000
weighted avg          0.8648  0.7481    0.7865  1600.0000